// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'bootloader.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `exchange`, `flash_inner`, `get_local_checksum`, `prepare_flash_chunks`, `read_exact`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Segment`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`

Stream<FlashState> flashFirmware({required String hexStr}) =>
    RustLib.instance.api.crateApiBootloaderFlashFirmware(hexStr: hexStr);

@freezed
sealed class FlashState with _$FlashState {
  const FlashState._();

  const factory FlashState.connecting() = FlashState_Connecting;
  const factory FlashState.erasing() = FlashState_Erasing;
  const factory FlashState.writing({
    required int progressPercent,
  }) = FlashState_Writing;
  const factory FlashState.verifying() = FlashState_Verifying;
  const factory FlashState.finished() = FlashState_Finished;
  const factory FlashState.error({
    required String message,
  }) = FlashState_Error;
}
